// This transform config was generated by Snaplet.
// Snaplet found fields that may contain personally identifiable information (PII)
// and used that to populate this file.
import { copycat, faker } from "@snaplet/copycat";
import type { Transform } from "./structure";
export const config: Transform = () => ({
  graphql: {
    _field({ row }) {
      return {
        name: copycat.fullName(row.name),
      };
    },

    _type({ row }) {
      return {
        name: copycat.fullName(row.name),
      };
    },
  },
  auth: {
    audit_log_entries({ row }) {
      return {
        ip_address: copycat.scramble(row.ip_address),
      };
    },

    identities({ row }) {
      return {
        provider: copycat.oneOf(row.provider, faker.locales.en.address.state),
      };
    },

    refresh_tokens({ row }) {
      return {
        parent: copycat.scramble(row.parent),
        token: copycat.scramble(row.token, {
          preserve: [],
        }),
      };
    },

    users({ row }) {
      return {
        email: copycat.scramble(row.email, {
          preserve: ["@", "."],
        }),
        phone: copycat.scramble(row.phone),
        role: copycat.scramble(row.role),
      };
    },
  },
  storage: {
    buckets({ row }) {
      return {
        name: copycat.fullName(row.name),
      };
    },

    migrations({ row }) {
      return {
        hash: copycat.scramble(row.hash),
        name: copycat.scramble(row.name),
      };
    },

    objects({ row }) {
      return {
        name: copycat.fullName(row.name),
      };
    },
  },
});
